pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER"
  docker:
    storage_driver: vfs
    repo: plugins/npm
    tag: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: NPM
  desc: Publish files and artifacts to a NPM registry
  type: publish
  image: plugins/drone-node
  labels:
    - publish
    - node
