pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-npm
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: NPM
  desc: Publish files and artifacts to a NPM registry
  type: publish
  image: plugins/drone-node
  labels:
    - publish
    - node
